spring:
  kafka:
    producer:
      client-id: avro-pos-simulator
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        # KafkaAvroSerializer depends on the schema registry so we need to specify it
        schema:
          registry:
            url: http://localhost:8081

application:
  configs:
    invoice:
      count: 60
    topic:
      name: avro-pos-topic